// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbhdleTlznfbiPQiF6RBm0s35rpI6_FbI',
    appId: '1:288228711775:web:71d02b2e26880c2a3a6aea',
    messagingSenderId: '288228711775',
    projectId: 'e-commerce-app-75715',
    authDomain: 'e-commerce-app-75715.firebaseapp.com',
    storageBucket: 'e-commerce-app-75715.firebasestorage.app',
    measurementId: 'G-8674VW5KT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_1lb839WV_kYDzmSqAus9vTn1EocDO-I',
    appId: '1:288228711775:android:38472b52f87f7e433a6aea',
    messagingSenderId: '288228711775',
    projectId: 'e-commerce-app-75715',
    storageBucket: 'e-commerce-app-75715.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI39k9xtyqzlR8-DOOhH4Whx-j5pdEogY',
    appId: '1:288228711775:ios:3971373f38c1b0fe3a6aea',
    messagingSenderId: '288228711775',
    projectId: 'e-commerce-app-75715',
    storageBucket: 'e-commerce-app-75715.firebasestorage.app',
    androidClientId: '288228711775-boffm8e9ekfamtkk5aprip6tmcv30psj.apps.googleusercontent.com',
    iosClientId: '288228711775-585sm1h4htcf42kmjb5fd02bkars751k.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI39k9xtyqzlR8-DOOhH4Whx-j5pdEogY',
    appId: '1:288228711775:ios:3971373f38c1b0fe3a6aea',
    messagingSenderId: '288228711775',
    projectId: 'e-commerce-app-75715',
    storageBucket: 'e-commerce-app-75715.firebasestorage.app',
    androidClientId: '288228711775-boffm8e9ekfamtkk5aprip6tmcv30psj.apps.googleusercontent.com',
    iosClientId: '288228711775-585sm1h4htcf42kmjb5fd02bkars751k.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbhdleTlznfbiPQiF6RBm0s35rpI6_FbI',
    appId: '1:288228711775:web:5534d19296bb270e3a6aea',
    messagingSenderId: '288228711775',
    projectId: 'e-commerce-app-75715',
    authDomain: 'e-commerce-app-75715.firebaseapp.com',
    storageBucket: 'e-commerce-app-75715.firebasestorage.app',
    measurementId: 'G-ZEG3LVMD6J',
  );
}
